### ISSUE TITLE
2.0.0-rc.0 copies files from dependencies within pnpm monorepo

### ISSUE THREAD

**Issue by gsong** [knightedcodemonkey/duel#46]
I have packages within a pnpm monorepo, and `duel` is copying files from dependency packages when compiling.

E.g. `package1` depends on `package2`, files from `package2` are copied into `pacakge1` upon compilation.

**Comment by knightedcodemonkey** [comment]
Thank you for reporting this. If you don't mind providing a general outline of your project structure, that would help. You can use an online tool like https://tree.nathanfriend.io/ to help with that.

**Comment by knightedcodemonkey** [comment]
@gsong I've released v2.0.0-rc.1 which should fix this issue.

**Comment by gsong** [comment]
> @gsong I've released v2.0.0-rc.1 which should fix this issue.

I’ll test it out soon and let you know.

**Comment by gsong** [comment]
> @gsong I've released v2.0.0-rc.1 which should fix this issue.

Can confirm this fixed my issue. Thank you!
